In [2]:
def greet(name):
    return f"Hello, {name}!"

print(greet("Manorma"))


Hello, Manorma!


In [3]:
#print a pattern

row = int(input("enter number of rows"))
cols = int(input("enter number of column"))
for i in range(0 ,row):
 for j in range(0,cols):
  if i%2==0:
   if j%2==0:
    print("#",end=" ")
   else:
    print("*",end=" ")
  else:
   if j%2!=0:
    print("#",end=" ")
   else:
    print("*",end=" ") 
 print("\n")  

enter number of rows 4
enter number of column 6


# * # * # * 

* # * # * # 

# * # * # * 

* # * # * # 



In [4]:
import numpy

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [6]:
import numpy as np
a=np.array([1,3,5])
b=np.array([3,5,6])
print(a+b)
print(a-b)
print(a*b)


[ 4  8 11]
[-2 -2 -1]
[ 3 15 30]


In [7]:
import numpy as np
arr=np.array([(2,3,4),(3,5,6),(4,5,6)])
print("shape is:",arr.shape)
print("size is:",arr.size)
print("data type:",arr.dtype)

shape is: (3, 3)
size is: 9
data type: int32


In [8]:
a = np.array([4,5,6,7,8,9])
print(a[0:6])  



[4 5 6 7 8 9]


In [9]:
import numpy as np

print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.eye((3)))
print(np.arange(2, 11, 3))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 5 8]


In [10]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(" 1D array:",arr)

 1D array: [10 20 30 40 50]


In [11]:
a = np.array([1, 2, 3])
b = np.array([5, 2, 3])
c=a+b
print("added array is:",c)
              

added array is: [6 4 6]


In [12]:
print("Range array:", np.arange(1, 10, 2))  # [1 3 5 7 9]


Range array: [1 3 5 7 9]


In [13]:
import numpy as np
arr = np.array([1,23,35,])
arr.ndim
arr.shape
arr.size
arr1 = np.full((2,4) , 8)
arr1


array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [14]:
np.sum(arr1 , axis = 1)

array([32, 32])

In [15]:
np.concatenate([a,arr])

array([ 1,  2,  3,  1, 23, 35])

In [16]:
import time

In [17]:
arr1.ravel()

array([8, 8, 8, 8, 8, 8, 8, 8])

In [18]:
arr1.flatten()

array([8, 8, 8, 8, 8, 8, 8, 8])